### ISSUE TITLE
서비스 기획

### ISSUE THREAD

**Issue by pjy0416** [boostcamp-2020/Project04-C-Whale#1]
# Discussion History

## 기획서
- [Web기획서](https://docs.google.com/presentation/d/1TJlCLFvrsmgS0QGRNYfjvJIuQG5WdjccmZ_hFBwSYX0/edit#slide=id.gac1437662e_0_0)
- [iOS 기획서](https://docs.google.com/presentation/d/1SKAsbqOwBOxV3_Sk6KH-YPnhxEfoJz9RlNhMQplhcvI/edit#slide=id.gac15425d6d_0_0)
- [Web Backlog](https://docs.google.com/spreadsheets/d/12ZqJbL0UhTdVH2FqpjqCzbunYzUg2QyLpx30rjz6T7Y/edit#gid=0)
- [iOS Backlog](https://docs.google.com/spreadsheets/d/12ZqJbL0UhTdVH2FqpjqCzbunYzUg2QyLpx30rjz6T7Y/edit#gid=336470392)

## 기획회의
+ 개인 vs 공동 중 개인을 위한 todo 서비스를 기획
+ 스크래치부터 기획하기에는 비용이 커서 레퍼런스로 Todoist 서비스 선정
+ 기본적인 기능은 todoist 와 유사하게 기획
+ 웨일 확장앱 API를 활용하여 todo서비스에 추가 구현할 수 있는 기능을 생각함.
    + 북마크
    + 캡처
+ 기능 기획의도
    + 기존 마크다운이나 트렐로에서는 흩어져있는 참고자료를 관리하기가 힘들었다.
    + 작업과 관련된 자료들을 한눈에 보기 쉽도록 제공한다.

#### 북마크
+ [whale.browserAction API 활용](https://developer.chrome.com/extensions/browserAction)
+ 웹앱 내부의 북마크 카테고리를 통해 작업에 대한 링크를 저장할 수 있다.
+ 웹앱에 저장된 북마크 목록을 웨일 브라우저의 북마크에 추가할 수 있다. 
+ iOS 앱과 웨일 북마크를 연동하려 했으나 iOS에서 웨일 api에 접근할 수 없기 때문에, 자체 서비스의 북마크를 도입

#### 캡처
+ [chrome.desktopCapture API 활용](https://developer.chrome.com/extensions/desktopCapture)
+ 브라우저 화면을 캡쳐한 이미지를 작업의 댓글로 저장할 수 있다.

**Comment by insanehong** [comment]
고민했던 내용들의 Topic 을 나눠서 개별 이슈로 등록하는게 좋습니다. 
예) 

##  Database 선정
  
하위할일 목록에 대한 DB설계에 있어서 SQL vs NOSQL을 도입할지 결정을 행야 할것같습니다. 

 - SQL
  - 장점: 블라블라브라
  - 단점: 블라블라블라

- NoSQL
  - 장점: 블라블라
  - 단점: 블라블라블라

**Comment by insanehong** [comment]
위 같은 이슈가 있을때 해당 이슈에서는 Database 선정에 대해서만 논의가 되겠죠?

물론 메신져나 온사이트에서 논의를 하더라도 결정된 내용과 이유를 남겨 놓거나 온사이트 논의가 불가능할때도 이슈에 comment 를 통해서 disscusion 을 이어 갈수 있으니 기록도 남고 이후에 왜 이런 결정을 했는지 혹은 다른 사람들과 공유하기도 좋겠죠?

실제 실무에서도 해야할일을 토픽단위로 이슈로 기록하고 이 이슈를 티켓을 업무를 할당합니다.

**Comment by insanehong** [comment]
이런식으로 해야 할 일들에 대한 토픽들 즉 해야 할 일들(Todo List)의 개념의 이슈들을 `backlog` 라고 부릅니다. 
이슈의 라벨기능을 이용해서 backlog 를 달아놓으면 더 좋겠죠 

그럼 수고하세요

**Comment by insanehong** [comment]
아 첨부해논 파일을 보니 backlog 의 개념은 알고 계신거 같군요... 근데 왜 이 이슈는 이런식으로...;;;

**Comment by pjy0416** [comment]
안녕하세요? 늦은 시간에 정말 감사합니다!!!
멘토님께서 슬랙에 팀의 고민사항이나 논의 사항에 대해서도 issue에 backlog로 작성하는 것이 좋다고 말씀하신 것을 보고, 기획사항을 이슈에 남겼습니다.
저희가 그동안 이슈에는 구현해야할 사항들만 작성하다보니 discussion history를 따로 남기지 않았었습니다.
그래서 이슈에 어떻게 작성해야하는지 몰라서 회의 내용 전체를 올려놨었습니다.
멘토님께서 리뷰해주신대로 고민 사항들을 나눠서 작은 단위로 관리하겠습니다 !!!!
