### ISSUE TITLE
Node 환경 설정

### ISSUE THREAD

**Issue by pjy0416** [boostcamp-2020/Project04-C-Whale#12]
### 구현 세부 사항
- [x] Express-generator를 이용해서 기본 서버 설정
- [x] eslint & prettier

**Comment by ed-jinyoung-park** [comment]
### 폴더구조
```
server
└───src
    ├───bin
    ├───config
    ├───controllers
    ├───loaders
    ├───models
    ├───routes
    ├───services
    └───app.js     
└───tests
```
#### loaders
app에서 실행시켜줘야할 loader들 (express loader, router, sequelize loader 등)을 따로 loader로 분리했습니다.

#### routes
각각의 route에 대한 controller를 연결해줍니다.

#### controllers
request에 대해 비즈니스로직을 수행하고 service를 거쳐 가공된 데이터를 response로 반환해줍니다.

#### services
DB와 통신하는 CRUD 로직을 담당합니다.
