### ISSUE TITLE
'관리함' 프로젝트 이름 변경 후 즐겨찾기 하면 사라지는 버그

### ISSUE THREAD

**Issue by ed-jinyoung-park** [boostcamp-2020/Project04-C-Whale#266]
'관리함' 프로젝트 이름 변경 후 즐겨찾기 하면 사라지는 버그입니다.

### AS-IS
* 유저 생성시 '관리함'이라는 이름으로 프로젝트 자동 생성
* 다른 프로젝트 생성시 '관리함'이라는 이름은 생성하지 못하도록 validation 처리되어있음
* 클라이언트에서 '관리함' 프로젝트 구분을 string으로 해주어 '관리함' 이름 변경시 필터링하지 못하는 문제 발생

### TO-BE
1,2 안중에 선택
1) '관리함' 프로젝트 구분을 createdAt이 제일 빠른 값을 찾는 것으로 로직을 바꾼다.
  * API에서 createdAt 값을 함께 넘겨줘야 한다.
2) project DB에 isDefault 칼럼을 추가하여 처음 생성되는 프로젝트에 isDefault: true 값을 부여
  * Client에서는 isDefault 값으로 '관리함' 프로젝트를 구분하는 로직으로 변경해야 한다.

제 의견은 1안이 더 좋아보입니다.
2안으로 할 경우 기존 생성되어있는 프로젝트에 isDefault 값을 부여하는 Query를 날려줘야 하는 번거로운 작업이 필요하기 때문입니다!

**Comment by shkilo** [comment]
토니가 말한 대로 2안은 관리함 하나 때문에 다른 모든 row 가 isDefault 필드를 가져야 하고,
DB를 바꾸는 것 보단 코드를 바꾸는 것이 덜 부담스럽기 때문에 1안이 좋아보입니다.

**Comment by pjy0416** [comment]
혹은 관리함 프로젝트는 이름을 바꿀 수 없게 하는 방안은 어떤가요?

**Comment by pjy0416** [comment]
이미 관리함 이름을 바꾼 유저도 있고, 자유도를 부여하는게 좋겠다는 의견을 받았고, 동의합니다 !!
저도 DB를 바꾸는 오버헤드 보다는 1번 방안으로 구분해도 지금 당장에서는 무리가 없다고 생각합니다.
