### ISSUE TITLE
Database 선정

### ISSUE THREAD

**Issue by shkilo** [boostcamp-2020/Project04-C-Whale#6]
### 논의 주제
**Database 선정**

### 논의 내용
+ 그동안 Mysql 을 많이 사용해 왔는데, mongodb 사용해보고 싶다는 의견이 있어 RDB 와 Nosql 의 장단점을 비교하고 우리 서비스에 맞는 db를 선정하고자 합니다.

#### SQL(RDBMS)
+ 장점 
   + 데이터의 중복을 피할 수 있다. (데이터 효율)
   + (join문을 통해서) 쿼리를 통해서 원하는 데이터를 조합하여 가져올 수 있다.
   + 커뮤니티가 크고, 익숙해서 접근성이 좋다.

+ 단점
   + 객체-관계형 매핑이 복잡해질 수 있다. (1:N, N:M ...)
   + 복잡한 시스템일수록 ERD 설계에 많은 시간이 소요된다.
   + 다양한 데이터 타입( Object, Array, List 등)을 저장할 수 없다.
   + 여러번의 join을 통해 query문이 복잡해질 수 있다.

#### NoSQL
+ 장점
   + 수평 확장에 용이하다. (데이터 베이스를 여러 대 두는 것이 용이)
   + JSON 도큐먼트를 그대로 조회 / 생성 할 수 있다.
   + 많은 데이터를 조회하고 생성하는게 주된 서비스에 용이하다. 

+ 단점
   + 테이블(도큐먼트) join이 불가능하기 때문에 원하는 형식으로 데이터를 직접 만들어야 한다.
   + 데이터의 중복 체크나 정합성 보장이 어렵다

#### 결정사항
NoSQL (mongoDB)를 사용하기로 결정!
- 할일 추가 시 해야하는 join 작업들이 많다 (label, project, 우선순위 등등..)
- 한 화면에서 조회해야 하는 테이블 개수가 많다.
- 팀 모두가 도전해보고 싶다는 의견이 일치

#### 용어 정리
+ 수평 확장
   + scale out => 서버를 여러 대로 증설
+ 수직 확장
   + scale up => 서버를 고성능으로 교체
+ 정합성
   + 데이터가 서로 모순이 없이 일관되게 일치

**Comment by ed-jinyoung-park** [comment]
#### 결정사항 수정
RDBMS (MySQL)을 사용하기로 결정했습니다!
근거는 다음과 같습니다.
- 조회, 생성도 많지만 수정, 삭제에서 연관된 테이블이 많아 foreign key가 없는 NoSQL에서 연산이 힘들 것이라고 판단
- ERD를 설계해봤을 때 따로 관리해야 하는 테이블들이 생각보다 많음
- 러닝커브를 고려했을 때 익숙한 MySQL로 가는것이 좋을 것 같다고 판단
