### ISSUE TITLE
Jest test 포트 점유 console error 처리

### ISSUE THREAD

**Issue by pjy0416** [boostcamp-2020/Project04-C-Whale#76]
### 논의 주제
Error: listen EADDRINUSE: address already in use :::3000 에러를 어떻게 해결할 것인가

### 논의 내용
- 병렬적으로 test가 실행되기 때문에  `--watchAll --maxWorkers=1` 옵션을 추가해서 하나의 테스트만 실행하도록 설정
   - 이 명령어로 해결되지 않았다.
   - 병렬 실행으로 인해 발생한 문제가 아니었다.
- app을 export할 때, 이미 3000번을 listen한 채로 넘겨받아서 생기는 문제일 수 있다.
   - listen 전에 export 하는 방법과, NODE_ENV가 test일 때는 listen을 하지 않도록 반영
   - 이 문제 또한 아니었다.
- beforeAll이 실행되기 전에 이전 테스트의 afterAll이 끝난 상황이 아니기 때문에 --detectOpenHandles 옵션이 적용되기 전이라 이전 테스트의 app이 아직 3000 port를 점유하고있다.
   - beforeAll, afterAll 의 위치를 describe 안쪽으로 scope를 이동시켜줬지만, 해결하지 못했다.
   - 하지만, beforeEach, afterEach로 변경하며 위치를 조정해줬는데, 비동기의 실행 상황 문제가 맞아 보인다. 이에 대해 논의가 필요함

- test 시, 포트를 0으로 설정해서 열려있는 포트로 작업하게끔 해결

**Comment by shkilo** [comment]
jest가 자체적으로 테스트를 병렬적으로 돌려서 생기는 문제인 것 같다.
테스트시 .env 의 port를 0으로 설정하는 것으로 해결했다.
참조링크 | https://stackoverflow.com/questions/54422849/jest-testing-multiple-test-file-port-3000-already-in-use
